name: trunk merge checks
on:
  pull_request: {}
  push:
    branches:
      - trunk-merge/**

jobs:
  test1:
    name: merge-test-1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run a test
        run: |
          git ls-remote
          git show HEAD

  test2:
    name: merge-test-2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run a test
        run: |
          true
